stat_svc
YaminoJakkaru/java-explore-with-me pull request #5
Opened 2023-05-17 11:04 UTC by YaminoJakkaru

2023-05-18 08:56 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Но есть некоторые замечания, которые необходимо исправить!

Желаю удачи!

2023-05-18 08:56 UTC, LexLippi commented on stats/stats-client/src/main/java/ru/practicum/stats/client/hit/HitClient.java
> +public class HitClient extends BaseClient {
Лучше делать все классы по возможности `final`, чтобы ни у кого не было желания унаследоваться от них и переопределить методы, не подумав можно ли это делать. Естественно за исключением тех, которые по твоей логике должны участвовать в наследовании.

2023-05-18 08:56 UTC, LexLippi commented on stats/stats-dto/src/main/java/ru/practicum/stats/dto/ViewedEndpointHitDto.java
> +    }
Аннотация `@Data` должна генерить ровно такой конструктор, зачем он тебе в явном виде?

2023-05-18 08:56 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/stats/hit/service/HitServiceImpl.java
> +                .setUri(storedEndpointHitDto.getUri());
Лучше это унести в класс `Mapper`

2023-05-18 08:56 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/stats/model/EndpointHit.java
> +    @Column(nullable = false, length = 512)
Даже очень извращенные `ipv6`-адреса имеют длину не более 45 символов в текстовом представлении. Так что 512 это слишком большой запас:

https://stackoverflow.com/questions/166132/maximum-length-of-the-textual-representation-of-an-ipv6-address

2023-05-18 08:56 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/stats/model/EndpointHit.java
> +    @Column(nullable = false, length = 512)
`URI` же может быть куда больше, на самом деле ограничения зависят от браузера и тп, но я бы советовал ориентироваться на длину в 2048 символов.

2023-05-18 08:56 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/stats/stats/StatsController.java
> +    private  final String DEFAULT_ENCODED_END = "999999999-12-31+00%3A2100%3A2100";
А поясни что это, а то выглядит диковато :)

2023-05-18 08:56 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/stats/stats/StatsController.java
> +                                               @RequestParam Optional<String[]> uris,
1. Зачем `Optional`
2. Зачем такая олдовая коллекция, как `String[]`

Я бы посоветовал использовать `List<String>`, и в качестве `defaultValue` использовать `List.of()`

2023-05-18 08:56 UTC, LexLippi commented on stats/stats-server/src/main/resources/schema.sql
> +    ip VARCHAR(512)                               NOT NULL,
Про ограничения на эти поля уже писал выше

2023-05-18 13:54 UTC, YaminoJakkaru commented on stats/stats-client/src/main/java/ru/practicum/stats/client/hit/HitClient.java
> +public class HitClient extends BaseClient {
исправлено

2023-05-18 13:54 UTC, YaminoJakkaru commented on stats/stats-dto/src/main/java/ru/practicum/stats/dto/ViewedEndpointHitDto.java
> +    }
исправлено

2023-05-18 13:54 UTC, YaminoJakkaru commented on stats/stats-server/src/main/java/ru/practicum/stats/hit/service/HitServiceImpl.java
> +                .setUri(storedEndpointHitDto.getUri());
исправлено

2023-05-18 13:54 UTC, YaminoJakkaru commented on stats/stats-server/src/main/java/ru/practicum/stats/model/EndpointHit.java
> +    @Column(nullable = false, length = 512)
исправлено

2023-05-18 13:54 UTC, YaminoJakkaru commented on stats/stats-server/src/main/java/ru/practicum/stats/model/EndpointHit.java
> +    @Column(nullable = false, length = 512)
исправлено

2023-05-18 13:55 UTC, YaminoJakkaru commented on stats/stats-server/src/main/java/ru/practicum/stats/stats/StatsController.java
> +    private  final String DEFAULT_ENCODED_END = "999999999-12-31+00%3A2100%3A2100";
исправлено

2023-05-18 13:55 UTC, YaminoJakkaru commented on stats/stats-server/src/main/java/ru/practicum/stats/stats/StatsController.java
> +                                               @RequestParam Optional<String[]> uris,
исправлено

2023-05-18 13:56 UTC, YaminoJakkaru commented on stats/stats-server/src/main/resources/schema.sql
> +    ip VARCHAR(512)                               NOT NULL,
исправлено

2023-05-19 07:33 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Есть пара замечаний, которые можно поправить к слелующему этапу дипломного проекта.

2023-05-19 07:33 UTC, LexLippi commented on stats/stats-client/src/main/java/ru/practicum/stats/client/hit/HitClient.java
> +    public HitClient(@Value("${stats.url}") String serverUrl, RestTemplateBuilder builder) {
Кстати `URL` лучше хранить, как `java.net.URI`, а не просто как строку

2023-05-19 07:33 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/stats/stats/StatsController.java
> +        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Форматер не стоит каждый раз создавать, его можно вообще статическим полем класса сделать

2023-05-19 07:33 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/stats/stats/StatsRepository.java
> +    @Query(value = "select new  ru.practicum.stats.dto.ViewedEndpointHitDto(e.app,e.uri ,count(e.ip))" +
Если сортируешь по счетчику то лучше ему название дать, чтобы каждый раз не писать вызов функции

2023-05-19 07:33 UTC, LexLippi commented on stats/stats-server/src/main/resources/schema.sql
> +create schema  public;
Можно ли как-то каждый раз не дропать это все?

2023-05-19 18:34 UTC, merged